# Generated by Django 6.0.5 on 2026-06-09 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HR', 'HR'), ('Technical', 'Technical'), ('Aptitude', 'Aptitude')], max_length=50)),
                ('answer', models.TextField()),
                ('feedback', models.TextField(blank=True)),
                ('score', models.FloatField(default=0)),
                ('communication_score', models.FloatField(default=0)),
                ('confidence_score', models.FloatField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Watch.interviewquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
