# Generated by Django 6.0.5 on 2026-06-18 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watch', '0002_interviewattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewattempt',
            name='body_language_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewattempt',
            name='eye_contact_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewattempt',
            name='fluency_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewattempt',
            name='grammar_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AptitudeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('time_taken', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('final_result', models.CharField(default='Fail', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Watch.interviewquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hiring_status', models.CharField(default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
