# Generated by Django 6.0.5 on 2026-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watch', '0003_interviewattempt_body_language_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewattempt',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
    ]
